name: Lexaday Update

on:
  schedule:
    - cron: "0 23 * * *"  # Daily at 23:00 UTC = 10:00 AM AEDT
  workflow_dispatch:

jobs:
  lexaday:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lexaday Update
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAILS: ${{ vars.RECEIVER_EMAILS }}
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          HF_API_TOKEN2: ${{ secrets.HF_API_TOKEN2 }}
          HF_API_TOKEN3: ${{ secrets.HF_API_TOKEN3 }}
          HF_API_TOKEN4: ${{ secrets.HF_API_TOKEN4 }}
          HF_API_TOKEN5: ${{ secrets.HF_API_TOKEN5 }}
          HF_API_TOKEN6: ${{ secrets.HF_API_TOKEN6 }}
          HF_API_TOKEN7: ${{ secrets.HF_API_TOKEN7 }}
          HF_API_TOKEN8: ${{ secrets.HF_API_TOKEN8 }}
          HF_API_TOKEN9: ${{ secrets.HF_API_TOKEN9 }}
          HF_API_TOKEN10: ${{ secrets.HF_API_TOKEN10 }}
          RECORDS_LINK: ${{ secrets.RECORDS_LINK }}
        run: |
          python lexaday.py

      - name: Commit and push updated files (including images)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add --all
          git commit -m "Update Lexaday data and images [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main